=== rhudock/sandbox-repo/learning-java/learning.java.lang/src/main/resources/cwl/learn/xml/sampledata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.cwl.com/xml/learn" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Hotel" type="lear:HotelType" xmlns:lear="http://www.cwl.com/xml/learn"/>
  <xs:complexType name="HotelType">
    <xs:sequence>
      <xs:element type="lear:DeviceType" name="Device" xmlns:lear="http://www.cwl.com/xml/learn"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
  </xs:complexType>
  <xs:complexType name="PortType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="portNumber" use="optional"/>
        <xs:attribute type="xs:string" name="roomRef" use="optional"/>
        <xs:attribute type="xs:string" name="zoneRef" use="optional"/>
        <xs:attribute type="xs:string" name="portTypeRef" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DeviceType">
    <xs:sequence>
      <xs:element type="lear:PortType" name="Port" maxOccurs="unbounded" minOccurs="0" xmlns:lear="http://www.cwl.com/xml/learn"/>
      <xs:element type="lear:DeviceAttrType" name="DeviceAttr" maxOccurs="unbounded" minOccurs="0" xmlns:lear="http://www.cwl.com/xml/learn"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="managementURI"/>
    <xs:attribute type="xs:string" name="deviceClass"/>
  </xs:complexType>
  <xs:complexType name="DeviceAttrType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="value" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== rhudock/sandbox-repo/learning-java/learning.java.lang/src/main/resources/cwl/learn/xml/sampledata.xml
<?xml version="1.0" encoding="UTF-8"?>
<Hotel name="Hiatt"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.cwl.com/xml/learn"
       xsi:schemaLocation="http://www.cwl.com/xml/learn /cwl/learn/xml/sampledata.xsd">

   <Device name="Device1" managementURI="10.1.100.4" deviceClass="Gateway">
      <Port portNumber="1" roomRef="Room1" zoneRef="Zone1" portTypeRef="PortType1"/>
      <Port portNumber="2" roomRef="Room2" zoneRef="Zone1" portTypeRef="PortType1"/>
      <Port portNumber="3" roomRef="Room3" zoneRef="Zone1" portTypeRef="PortType1"/>
      <Port portNumber="4" roomRef="Room4" zoneRef="Zone1" portTypeRef="PortType1"/>
      <Port portNumber="5" roomRef="Room5" zoneRef="Zone1" portTypeRef="PortType1"/>
      <Port portNumber="6" roomRef="Room6" zoneRef="Zone1" portTypeRef="PortType1"/>
      <Port portNumber="7" roomRef="Room7" zoneRef="Zone1" portTypeRef="PortType1"/>
      <Port portNumber="8" roomRef="Room8" zoneRef="Zone1" portTypeRef="PortType1"/>
      <Port portNumber="9" roomRef="Room9" zoneRef="Zone1" portTypeRef="PortType1"/>
      <Port portNumber="10" roomRef="Room10" zoneRef="Zone1" portTypeRef="PortType1"/>
      <DeviceAttr name="manufacturer" value="Nomadix"/>
      <DeviceAttr name="deviceType" value="NSE"/>
   </Device>

</Hotel>
